### ISSUE TITLE
Multiple loader, only last launch on start

### ISSUE THREAD

**Issue by Afondevi** [t-ho/ngx-ui-loader#11]
Hello, 

I try to run 2 loaders in same time with different loader id for each : 

```
 ngxLoaders = ['load-user','load-friends'];
    ....
    startLoad(): void{
        this.ngxLoaders.map(loaderId => {
            this.ngxService.startLoader(loaderId);
        });
    }

    ngOnInit() {
        this.startLoad();
        ....
    }
```

html => 
```
<div style="position:relative;">
    <ngx-ui-loader [loaderId]="'load-users'"></ngx-ui-loader>
</div>
<div style="position:relative;">
    <ngx-ui-loader [loaderId]="'load-friends'"></ngx-ui-loader>
</div>
```
Only the last one running, can you tell me why please ? how fix it ?

Thanks !

**Comment by t-ho** [comment]
Hi @Afondevi,

Thanks for your feedback!

The issue has been addressed in 95e8581b7652dd56f19937533dd51f64f8c95e7d.

And I have release 7.1.0.beta.3, please give it a try!

Best regards
