### ISSUE TITLE
how to ngx-ui-loader to show forground image  only, not a forground spinner

### ISSUE THREAD

**Issue by Madasamy26** [t-ho/ngx-ui-loader#12]
how to show only a forground image not a forground spinner?

can i do that?.

**Comment by t-ho** [comment]
Hi @Madasamy26,

There is a workaround, just set `[fgsSpinner]="0"`. For example:

```html
<ngx-ui-loader [fgsSize]="0" [logoUrl]="'https://raw.githubusercontent.com/t-ho/ngx-ui-loader/master/src/assets/angular.png'"></ngx-ui-loader>
```
I hope this will help.

**Comment by Madasamy26** [comment]
Hi @t-ho 
Yes your sample code  is working  fine.

Thanks
