### ISSUE TITLE
Master Loader not automatically working when navigating between app routes on using non-master

### ISSUE THREAD

**Issue by kathiravan** [t-ho/ngx-ui-loader#13]
Master Loader not automatically working when navigating between app routes on using non-master in other pages.

**Comment by ryanglue** [comment]
You have to make sure your non-master component available to pages you navigate to. Otherwise, nothing is showed. Why don't you use master loader?

**Comment by kathiravan** [comment]
In a page i am using both master loader(by default called from app.component)  and non-master loader specific to pages (on section based http post call). 

My issue is If non-master loader been implemented, master loader doesn't called between the routes. 

App.Module
---------------

const ngxUiLoaderConfig: NgxUiLoaderConfig = {
  // bgsColor: '#OOACC1',
  // bgsOpacity: 0.5,
  // bgsPosition: POSITION.bottomCenter,
  // bgsSize: 60,
  // bgsType: SPINNER.rectangleBounce,


  fgsColor: '#00ACC1',
  fgsPosition: POSITION.centerCenter,
  fgsSize: 60,
  fgsType: SPINNER.threeStrings,

  // logoUrl: '../assets/truckicon.png',
  pbColor: '#FF0000',
  pbDirection: PB_DIRECTION.leftToRight,
  pbThickness: 5,

  text: 'Loading',
  textColor: '#FFFFFF',
  textPosition: POSITION.centerCenter
};

    NgxUiLoaderModule.forRoot(ngxUiLoaderConfig),
    NgxUiLoaderRouterModule,
    NgxUiLoaderHttpModule


App.component: (Master loader works only if below not non-master loader implemented)
-----------------

<ngx-ui-loader></ngx-ui-loader> 
<router-outlet></router-outlet>

Home.Component:
------------------
<div style="position:relative" >
       <div  ngxUiLoaderBlurred  [loaderId]="'loader-01'" >
        </div>
         <ngx-ui-loader [loaderId]="'loader-01'"></ngx-ui-loader>
</div>
