### ISSUE TITLE
Progress bar not showing/working

### ISSUE THREAD

**Issue by subotin94** [t-ho/ngx-ui-loader#14]
Progress bar not showing on multiple projects where we included this library. Config:

const ngxUiLoaderConfig: NgxUiLoaderConfig = {
  bgsColor: '#005697',
  bgsPosition: POSITION.topRight,
  bgsOpacity: 1,
  bgsSize: 20,
  bgsType: SPINNER.wanderingCubes,
  masterLoaderId: 'loader-01',
  blur: 0,
  hasProgressBar: true,
  pbColor: '#005697',
  pbDirection: PB_DIRECTION.leftToRight,
  pbThickness: 5,
  threshold: 500
}

**Comment by t-ho** [comment]
I really don't understand what you are trying to do.

Please read [README](https://github.com/t-ho/ngx-ui-loader) carefully and see examples that I provided in the docs.

If you need help, please give your simple setup on [Stackblitz](https://stackblitz.com/).

Thanks!
