### ISSUE TITLE
Non-master Loader not working on Angular Module/Feature level Architecture

### ISSUE THREAD

**Issue by kathiravan** [t-ho/ngx-ui-loader#15]
Hi, 

Looks like non-master Loader not working on Angular Module/Feature level Architecture

I have imported NgxUiLoaderModule.forRoot(ngxUiLoaderConfig), NgxUiLoaderRouterModule, NgxUiLoaderHttpModule in app.module. 

NgxUiLoaderRouterModule - Works will across routes, but non-master loader throws error. 

[ERROR ->]<ngx-ui-loader [loaderId]="'loader-ref1'"></ngx-ui-loader>
'ngx-ui-loader' is not a known element

Can you please help me to fix it?

**Comment by t-ho** [comment]
You have to import `NgxUiLoaderModule` into your feature module to use non-master loader.
