### ISSUE TITLE
NgxUiLoaderHttpModule not working correctly in lazy loaded module in angular 4 

### ISSUE THREAD

**Issue by Madasamy26** [t-ho/ngx-ui-loader#16]
Hi @t-ho:

I am using NgxUiLoaderHttpModule in app.module.ts for showing spinner in all lazy loaded module while making httpRequest, 

The way I was using that 

In app.module.ts 

Imports : [
NgxUiLoaderHttpModule.forRoot({ showForeground: true })
]

In other lazy loading module,

import : [
NgxUiLoaderModule.forRoot(ngxUiLoaderConfig),
]

Appropriate module having the selector of <ngx-ui-loader></ngx-ui-loader> in html file 

**The Problem was, In my project one lazy loaded module showing spinner perfectly but other modules are not showing ??**

**Comment by t-ho** [comment]
You should import `NgxUiLoaderModule` in your `app.module.ts` file (**NOT** in your lazy loading module).
```typescript
imports: [
    NgxUiLoaderModule.forRoot(ngxUiLoaderConfig),
    NgxUiLoaderHttpModule.forRoot({ showForeground: true }),
]
```

**Comment by Vsatishbabu** [comment]
those both are added in app.module.ts but no use.
