### ISSUE TITLE
7.2.0 - compile issue

### ISSUE THREAD

**Issue by mathieurousseau** [t-ho/ngx-ui-loader#19]
going back to 7.1.2 fixes the issue

`ERROR in node_modules/ngx-ui-loader/lib/http/ngx-ui-loader-http.interceptor.d.ts(3,36): error TS2307: Cannot find module '../core/ngx-ui-loader.service'.
node_modules/ngx-ui-loader/lib/router/ngx-ui-loader-router.module.d.ts(3,36): error TS2307: Cannot find module '../core/ngx-ui-loader.service'.
node_modules/ngx-ui-loader/ngx-ui-loader.d.ts(5,51): error TS2307: Cannot find module './lib/core/ngx-ui-loader-blurred.directive'.
node_modules/ngx-ui-loader/ngx-ui-loader.d.ts(6,50): error TS2307: Cannot find module './lib/core/ngx-ui-loader-config.token'.
node_modules/ngx-ui-loader/ngx-ui-loader.d.ts(7,44): error TS2307: Cannot find module './lib/core/ngx-ui-loader.component'.
node_modules/ngx-ui-loader/public_api.d.ts(1,36): error TS2307: Cannot find module './lib/core/ngx-ui-loader.service'.
node_modules/ngx-ui-loader/public_api.d.ts(2,35): error TS2307: Cannot find module './lib/core/ngx-ui-loader.module'.
node_modules/ngx-ui-loader/public_api.d.ts(3,35): error TS2307: Cannot find module './lib/core/ngx-ui-loader-config'.
node_modules/ngx-ui-loader/public_api.d.ts(4,49): error TS2307: Cannot find module './lib/core/ngx-ui-loader.enums'.
node_modules/ngx-ui-loader/public_api.d.ts(5,39): error TS2307: Cannot find module './lib/core/ngx-ui-loader.interfaces`

**Comment by mathieurousseau** [comment]
I checked and I could not find core folder under lib folder

**Comment by t-ho** [comment]
Hi @mathieurousseau,

Thanks for your feedback!

This issue is related to [npm-cli@6.8.0 bug](https://npm.community/t/npm-v6-8-0-pack-publish-not-bundling-folders-named-core/5727).

I republished the package.
