### ISSUE TITLE
There are any way to set a timeout to NgxUiLoaderHttpModule?

### ISSUE THREAD

**Issue by RafaelFronteira** [t-ho/ngx-ui-loader#20]
I'm really not found in the docs or in issues if it is possible set this.

Thanks a lot!

**Comment by t-ho** [comment]
Hi @RafaelFronteira,

Sorry for late response.

We can't set a timeout with the current implementation.

You may write your own Http-interceptor that meets your needs. Take a look [here](https://stackoverflow.com/questions/45938931/default-and-specific-request-timeout/45986060#45986060). I hope it will help.

Thanks!
