### ISSUE TITLE
ngx ui loader is showing error while manually start and stop the ngxUiLoaderService

### ISSUE THREAD

**Issue by Madasamy26** [t-ho/ngx-ui-loader#23]
<ngx-ui-loader></ngx-ui-loader> ngx-ui-loader I am using across the modules , and I have one loader interceptor that should start and stop the loader manually while making http call. 
but below warning is message is showing after second time loader showing,
![ngx-ui-loader-error](https://user-images.githubusercontent.com/25219678/55346038-15126000-54cf-11e9-94b3-399037979f17.PNG)

can you help me on that?

**Comment by t-ho** [comment]
Did you place `<ngx-ui-loader>` selector in your root template?

**Comment by Madasamy26** [comment]
yes I have placed selector in template , when the error is occuring, for example assume that I have two modules , In that two modules I have <ngx-ui-loader>, while I am clicking on first module,loader is showing, after clicking on second module the loader is showing but warning message is showing ,like above unsubscriberErrorImpl.

**Comment by t-ho** [comment]
Could you please add a basic reproduction using a [stackblitz](https://stackblitz.com)?
