### ISSUE TITLE
NgxUiLoaderConfig not working

### ISSUE THREAD

**Issue by raphaelramos** [t-ho/ngx-ui-loader#25]
NgxUiLoaderConfig is not applied. No error in console.
ngx-ui-loader 7.2.2. angular 7.2.14.

//app.module
import { NgxUiLoaderModule, NgxUiLoaderConfig, SPINNER } from 'ngx-ui-loader';

const ngxUiLoaderConfig: NgxUiLoaderConfig = {
  bgsType: SPINNER.ballScaleMultiple,
  hasProgressBar: false
};

imports: [
   NgxUiLoaderModule.forRoot(ngxUiLoaderConfig)
],

//component
import { NgxUiLoaderService } from 'ngx-ui-loader';
constructor(private ngxService: NgxUiLoaderService) {}
this.ngxService.start();

**Comment by cmwittrock** [comment]
Did you remember to add the `<ngx-ui-loader></ngx-ui-loader>` tag to your component?

**Comment by raphaelramos** [comment]
Yes. It works, but does not use the module configuration, as spinner.

**Comment by t-ho** [comment]
Hi @raphaelramos,

You need to use `fgsType` (foreground spinner type) instead of `bgsType` (background spinner type) in your `ngxUiLoaderConfig` constant.

**Comment by raphaelramos** [comment]
Thank you
