### ISSUE TITLE
ngxUiLoader fadeout speed

### ISSUE THREAD

**Issue by mnesser** [t-ho/ngx-ui-loader#26]
Is it possible to increase the fadeout speed of the loader?
i.e. the time from `this.ngxLoader.stopLoader('xxx');` to the ngx-ui-loader is hidden.

**Comment by t-ho** [comment]
No, it isn't.
Sorry for that.

**Comment by t-ho** [comment]
Hi @mnesser,

FYI, In version 9.1.0, you can shorten the fadeout duration by setting `fastFadeOut` to `true`. Also, you can use your own custom template. Please see the documentation [here](https://tdev.app/ngx-ui-loader).

Best regards,
