### ISSUE TITLE
Excluding specific path from NgxUiLoaderRouter

### ISSUE THREAD

**Issue by fdinardo** [t-ho/ngx-ui-loader#27]
Hi @t-ho,
I really appreciate your work! Thanks.

I was wondering if it's possible to exclude some routes for `NgxUiLoaderRouter`.

Use Case:
I have a very common Admin panel, and when the user navigates the application after login, I am really happy with `NgxUiLoaderRouter`. 
But when the user logs out, I don't want to show them the loader on the redirected login page.

Is that possible? If not, do you think it's something you are going to implement at some point?

Thanks

**Comment by piemanvik** [comment]
Hi @t-ho,
I really appreciate your work! Thanks.

I was just wondering the same thing my use case is more complex however I will say that it involves auxiliary routes and I want to use different loaders for them. Would be nice to be able to tell the NgxUiLoaderRouter to ignore certain routes. In the mean time I will see if I can do something on my own by start/stop loader on route changes.

Thank you.

**Comment by t-ho** [comment]
Hi,
I updated the lib. Please check it out.
