### ISSUE TITLE
ngx-overlay not covering full page when it has scrolling

### ISSUE THREAD

**Issue by devit** [t-ho/ngx-ui-loader#28]
Hi, if I have a page longer that the screen using

`<div ngxUiLoaderBlurred blur="10" style="height:100%;" [loaderId]="'global_blur'" >`
`  <router-outlet></router-outlet>`
`</div>`
`<ngx-ui-loader`
`[overlayColor]="'rgba(40,40,40,.5)'"` 
`[loaderId]="'global_blur'" `
`[text]="'working...'"`
`[textColor]="'#FFF'"`
`[hasProgressBar]="'false'"`
`></ngx-ui-loader>`

the whole page is blurred but overlay only reaches to the bottom of the visible screen, so there is no overlay on the scrolled section, also the spinner and the background scrolls up and down with the screen

Thanks for any advise on how to fix this

**Comment by t-ho** [comment]
Hi @devit,

You should use master loader, instead of non-master loader. So you don’t need to change the `loaderId`. Please see [here](https://github.com/t-ho/ngx-ui-loader/wiki/Getting-started#24-multiple-loaders).

Thank you!
