### ISSUE TITLE
How to use it with multiple feature modules? 

### ISSUE THREAD

**Issue by kavin404** [t-ho/ngx-ui-loader#30]
I have tried to use this library after importing NgxUiModule in AppModule.  It gives me this error "'ngx-ui-loader' is not a known element:". I also tried to move it to FeatureModule but then it says "you have already imported NgxUiModule in AppModule" what should I do?

**Comment by t-ho** [comment]
Hi @kavin404,

Please see simple setup [here](https://stackblitz.com/edit/ngx-ui-loader-with-feature-module).

Thanks
