### ISSUE TITLE
Not sure if current http interceptor is interferring with loader

### ISSUE THREAD

**Issue by netbitshift** [t-ho/ngx-ui-loader#31]
Im trying to use the "minimal" setup for the 7.2x version, as I am using Angular 7.  However, Im currently using a single HttpInterceptor that shows a small progress spinner at the top of my page.  It works, but when I try to use ngx-ui-loader with just a minimal example (as example [here](https://stackblitz.com/edit/ngx-ui-loader-minimal-setup)), my progress bar shows, but the loader does not.  Do I need to disable my current interceptor?

**Comment by netbitshift** [comment]
Disregard.  I hadn't followed the instructions all the way :) 👍

**Comment by thinkards** [comment]
> Disregard. I hadn't followed the instructions all the way :)

What did you learn?  I'm having the same problem.
