### ISSUE TITLE
How to override the spinner image?

### ISSUE THREAD

**Issue by netbitshift** [t-ho/ngx-ui-loader#32]
Is there a way to override the image or use a different spinner or animated gif?

**Comment by t-ho** [comment]
Sorry, the lib does not support this.

**Comment by t-ho** [comment]
Hi @netbitshift,

FYI, You can use your own spinner now in `ngx-ui-loader@9.1.0`. See the documentation [here](https://tdev.app/ngx-ui-loader#custom-template)

**Comment by MincDev** [comment]
@t-ho I tried adding a gif to my ng-template but does not seem to show. Is gif's supported?
