### ISSUE TITLE
How to set spinner to load only for httpget requests

### ISSUE THREAD

**Issue by shan75** [t-ho/ngx-ui-loader#33]
Hi
How to set spinner to load only for httpget requests.  I guess one way of doing it may be to manually start and stop in httpinterceptor.  Is there any other of loading spinner only for http get requests?

**Comment by cmwittrock** [comment]
While not specific to GET requests, you can exclude the spinner when accessing certain URLs using exclude or excludeRegexp when configuring the NgxUiLoaderHttpModule

```
NgxUiLoaderHttpModule.forRoot({
      showForeground: true,
      // exclude: [
      //   'http://localhost:7101/App/someurl',
      //   'http://localhost:7101/App/logout'
      // ]
      excludeRegexp: ['/someUrl$', '/logout.html$']
    }),
```
