### ISSUE TITLE
Reading Data from Cache does not trigger Loader

### ISSUE THREAD

**Issue by JohnSeals** [t-ho/ngx-ui-loader#34]
Hello there. Great project by the way!

I make a call to an API service that loads about 2000 plus records. So I make the call once on app startup/page load, and then hit a simple cache I made after that. Here's the code in the service:
```
    getAllApis(): Observable<Apidata> {
      if (!this.cache) {
        console.log('cache empty => refreshing');
        this.cache = this.http.get<Apidata>(`${this.apiSearch}` + '/apis').pipe(
          takeUntil(this.reload),
          shareReplay(1),
          retry(1),
          catchError(this.handleError)
        );
      }
        return this.cache;
    }
```

The rest of the setup is just like ij the examples you provide.
The problem I am having is that when I an reading from the cache ngx-ui-loader will not load the "spinner." 
The first time I hit the serivce, thus no cache, it works great. I have tried using NgxUiLoaderHttpModule but it doesn't work. I have also tried starting the spinner in the service, and loading it manually in different parts of the component pge but no luck. 
Is there a way to get the spinner to load in this instance?
Thanks . . .

**Comment by t-ho** [comment]
Hi @JohnSeals,

Use `NgxUiLoaderHttpModule` for http requests. And you have to start and stop loader manually for other cases.
```typescript
getAllApis(): Observable<Apidata> {
      this.ngxUiLoaderService.startBackground('cached'); // <--- start background loader
      if (!this.cache) {
        console.log('cache empty => refreshing');
        this.cache = this.http.get<Apidata>(`${this.apiSearch}` + '/apis').pipe(
          takeUntil(this.reload),
          shareReplay(1),
          retry(1),
          catchError(this.handleError)
        );
      }
      this.ngxUiLoaderService.stopBackground('cached'); // <--- stop background loader
      return this.cache;
    }
```

**Comment by JohnSeals** [comment]
Sorry for my late reply. Thanks! It's working great. I appreciate your help.
