### ISSUE TITLE
Subscribe to Loader events

### ISSUE THREAD

**Issue by FireDrunk** [t-ho/ngx-ui-loader#35]
Is there a way to subscribe to start/stop events for a loader with a specific name?
I would like to show text in a table saying that there are no items yet depending on a specific loader that is running in the background.

Also, kudo's for the awesome lib!

**Comment by t-ho** [comment]
Hi @FireDrunk,

It can be achieved by using [multiple-loader](https://github.com/t-ho/ngx-ui-loader/wiki/Getting-started#24-multiple-loaders) and [Service API](https://github.com/t-ho/ngx-ui-loader/wiki/API---NgxUiLoaderService).

If you really want to subscribe to start/stop events, please see the [service file](https://github.com/t-ho/ngx-ui-loader/blob/master/projects/ngx-ui-loader/src/lib/core/ngx-ui-loader.service.ts) (`showForeground$`, `showBackground$`, `foregroundClosing$`, `backgroundClosing$` are what you are looking for). However, these properties are for internal use only, they may be changed in the future. So it is not recommended.
