### ISSUE TITLE
ngx-ui-loader with exclude option is not working.

### ISSUE THREAD

**Issue by ssingana** [t-ho/ngx-ui-loader#37]
I have added the ngx-ui-loader with the exclude option 
NgxUiLoaderHttpModule.forRoot({ excludeRegexp : ['/api/asdfasdf\?var=\d{3}$','/api/asdfasdf\?model=\d{3}$','/api/asdfasdf\?model=\d{3}$'], showForeground: true })

But still the progress spinner is showing for the above rest api calls also.

**Comment by t-ho** [comment]
Hi @ssingana,
Sorry for late response.

I guess your regex-es are incorrect because the `sdf?var` matches `sdvar` or `sdfvar`. The `?` matches zero or one time, so it should be escaped as below:
```typescript
NgxUiLoaderHttpModule.forRoot({ excludeRegexp : ['/api/asdfasdf\?var=\d{3}$','/api/asdfasdf\?model=\d{3}$','/api/asdfasdf\?model=\d{3}$'], showForeground: true })
```
