### ISSUE TITLE
Improvement: Only show Progress-bar

### ISSUE THREAD

**Issue by Logic-Bits** [t-ho/ngx-ui-loader#38]
It would be helpful to only show the top bar and maybe also to set a progress in percent.

Love your work!

**Comment by ShivPandey** [comment]
Is there any option to show only progress bar on router event?

**Comment by t-ho** [comment]
@Logic-Bits To show the progress bar only, set the spinner size to zero.

@ShivPandey To workaround, you can set the spinner size to zero by default; for the other cases, implement your own service to set the spinner size back to normal. See an example [here](https://stackblitz.com/edit/ngx-ui-loader-customized-service)

**Comment by w3villa-technologies** [comment]
Hi, thankyou for the input @t-ho , can you also point out if there's a way to make page clickable while progress bar is loading? I don't want to restrict users using the page until all the components are loaded. User should be able to click and navigate while processing of page in in progress. Is there a workaround for this?
