### ISSUE TITLE
NgxUiLoaderHttpModule screen stuck on mouse hover spinning

### ISSUE THREAD

**Issue by vsarunov** [t-ho/ngx-ui-loader#42]
Running loader with NgxUiLoaderHttpModule.forRoot({ showForeground: true }) the spinner appears, when all the request are finished it disappear, however the screen is still stuck and there is a spinner near the mouse when you hover over the page. 

What I have tried so far:
1. Leaving only one request to test it, still the same.
2. Tried blocking some request.
3. Setting min/max time.

Loader config:

```
const ngxUiLoaderConfig: NgxUiLoaderConfig = {
    fgsColor: '#00aed9',
    fgsPosition: 'center-center',
    fgsSize: 60,
    fgsType: 'folding-cube',
    overlayBorderRadius: '0',
    overlayColor: 'rgba(40,40,40,0)',
    hasProgressBar: false
};
```
   ```
     NgxUiLoaderModule.forRoot(ngxUiLoaderConfig),
        NgxUiLoaderHttpModule.forRoot({ showForeground: true })
```

Please note I have the HttpModule in sub module the loader config in main module.

Using Angular 8.

**Comment by kamlesh0606** [comment]
try With  `minTime: 1` in NgxUiLoaderConfig .
