### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using NgxUiLoaderHttpModule

### ISSUE THREAD

**Issue by ArgV04** [t-ho/ngx-ui-loader#45]
I got the following error when using NgxUiLoaderHttpModule in my Angular 8 app

Config seems straight forward:

```
const ngxUiLoaderConfig: NgxUiLoaderConfig = {
  fgsType: SPINNER.squareJellyBox, // background spinner type
  fgsColor: '#ec0016'
};

@NgModule({
  declarations: [
    AppComponent,
    ToolbarComponent,
    FooterComponent,
  ],
  imports: [
    ...
    HttpClientModule,
    NgxUiLoaderModule.forRoot(ngxUiLoaderConfig),
    NgxUiLoaderHttpModule.forRoot({ showForeground: true })
...
```
In my app.component.html I added the html-tag:

`<ngx-ui-loader></ngx-ui-loader>`

But during app loading I got this console output:

```
NgxUiLoaderComponent.html:2 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'loading-foreground: undefined'. Current value: 'loading-foreground: true'.
    at viewDebugError (core.js:28792)
    at expressionChangedAfterItHasBeenCheckedError (core.js:28769)
    at checkBindingNoChanges (core.js:29757)
    at checkNoChangesNodeInline (core.js:44448)
    at checkNoChangesNode (core.js:44415)
    at debugCheckNoChangesNode (core.js:45376)
    at debugCheckRenderNodeFn (core.js:45308)
    at Object.eval [as updateRenderer] (NgxUiLoaderComponent.html:2)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:45293)
    at checkNoChangesView (core.js:44250)
```

Any ideas?

**Comment by simplenetworks** [comment]
Same problem with last version. Any news?

**Comment by ArgV04** [comment]
No comments regarding this issue?

**Comment by vTodorov** [comment]
+1

**Comment by storytellerr** [comment]
+1

**Comment by wakkasha** [comment]
+1

**Comment by t-ho** [comment]
Could you please provide a basic reproduction using a [stackblitz](https://stackblitz.com/)?

And there are some examples [here](https://github.com/t-ho/ngx-ui-loader/wiki/Demo). They might help you out.

Thanks.

**Comment by ozgurtunc93** [comment]
+1

**Comment by CR903** [comment]
angular8
cli

![image](https://user-images.githubusercontent.com/7643647/82039870-34228000-96d8-11ea-8fa0-8d5524acd5c6.png)

**Comment by decoder318** [comment]
I use a single loader. And use it in the NgxUiLoaderHttpModule like this:

```
NgxUiLoaderHttpModule.forRoot({
      showForeground: true,
      excludeRegexp: [
        'school-open-worktray-group-count',
        'mark-as-read',
      ]
}),
```

My app component is like this

```
<div class="content-wrapper">
  ...Some thing here...
</div>
<ngx-ui-loader fgsColor="#ffffff" overlayColor="rgba(40, 40, 40, 0.5)"></ngx-ui-loader>
```

Everytime, I open a component (which has an ajax call in it) via Angular Material Dialog service, I get this in the console.

![image](https://user-images.githubusercontent.com/6450986/95767306-498bec80-0d00-11eb-8dcf-ca664b0d3f38.png) 

I tried without using the NgxUiLoaderHttpModule, and wrote my own Http Interceptor to start or stop the spinner. Same thing happens. It's not the worst thing, as in it does not affect the functionality. But still, it bugs me.

@t-ho Is there any chance, I can get over it, without upgrading my app to Angular 9?

**Comment by portus84** [comment]
+1 Still occurs

**Comment by DominicBisschop** [comment]
This problem still occurs on our project. How is this issue closed when the problem still persists? How can I fix this error in the debugger console? Thanks in advance.

**Comment by DominicBisschop** [comment]
> I got the following error when using NgxUiLoaderHttpModule in my Angular 8 app
> 
> Config seems straight forward:
> 
> ```
> const ngxUiLoaderConfig: NgxUiLoaderConfig = {
>   fgsType: SPINNER.squareJellyBox, // background spinner type
>   fgsColor: '#ec0016'
> };
> 
> @NgModule({
>   declarations: [
>     AppComponent,
>     ToolbarComponent,
>     FooterComponent,
>   ],
>   imports: [
>     ...
>     HttpClientModule,
>     NgxUiLoaderModule.forRoot(ngxUiLoaderConfig),
>     NgxUiLoaderHttpModule.forRoot({ showForeground: true })
> ...
> ```
> 
> In my app.component.html I added the html-tag:
> 
> `<ngx-ui-loader></ngx-ui-loader>`
> 
> But during app loading I got this console output:
> 
> ```
> NgxUiLoaderComponent.html:2 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'loading-foreground: undefined'. Current value: 'loading-foreground: true'.
>     at viewDebugError (core.js:28792)
>     at expressionChangedAfterItHasBeenCheckedError (core.js:28769)
>     at checkBindingNoChanges (core.js:29757)
>     at checkNoChangesNodeInline (core.js:44448)
>     at checkNoChangesNode (core.js:44415)
>     at debugCheckNoChangesNode (core.js:45376)
>     at debugCheckRenderNodeFn (core.js:45308)
>     at Object.eval [as updateRenderer] (NgxUiLoaderComponent.html:2)
>     at Object.debugUpdateRenderer [as updateRenderer] (core.js:45293)
>     at checkNoChangesView (core.js:44250)
> ```
> 
> Any ideas?

Has anybody found a solution for this annoying error in the console?
