### ISSUE TITLE
Logo Width and Logo Height

### ISSUE THREAD

**Issue by VladimirRadeski** [t-ho/ngx-ui-loader#46]
Can you add logoHeight and logoWidth configuration properties instead of logoSize?

**Comment by t-ho** [comment]
To work around, you can add transparent padding to your logo.

**Comment by iX-yse** [comment]
First of all thank you for this repository! Would be very nice if you could add the functionallity of setting logoWidth and logoHeight. Don't think this is a big deal.

Thanks
