### ISSUE TITLE
Not Work in Subscriber 

### ISSUE THREAD

**Issue by dreamid27** [t-ho/ngx-ui-loader#5]
Hi, thank for awesome plugin. but i got some problem when implement this package in my project.

I try to run loader before Observable area , and I'm try to stop loader in Observable, but loader not stopped.

maybe my code is wrong, or it's real bug , can i stop it in observable area ? it's possible ?? thank before

this is my code, 

`	this.spinner.start();
		const objModel = this.mergeModel();
		this.roleFormService.addRole(objModel)
			.subscribe((data) => {
				if (!data.isError) {
					this.roleForm.reset();
				}
				this.spinner.stop();
			}, error => console.log(error));`

this.spinner mean package ngx-ui-loader, sorry for bad english, make you confusing.

**Comment by t-ho** [comment]
Hi @dreamid27,
The package works correctly. You can have a look [here](https://stackblitz.com/edit/ngx-ui-loader-minimal-setup?file=src/app/app.component.ts) for a minimal setup.
Thanks.

**Comment by dreamid27** [comment]
@t-ho i'm sorry about bad information. I'm an experiment in some case, so I found the problem it's not about Observable.

I'm trying with method 'SetTimeout', the loading couldn't stop.

this package have dependency ? 

I'm not using Material Theme from angular.,  if the loader run method start, it's work perfectly, but when I stop it,  won't stop.

and i'm experiment install this package in theme Metronic Angular version https://keenthemes.com/metronic/preview/angular/default/.  

if you have,  you can try it using metronic angular version.

I don't feel wrong, I follow all instruction how to use it and check again and again maybe I found my mistakes. but it's not.

Thank before.

**Comment by dreamid27** [comment]
![image](https://user-images.githubusercontent.com/22621375/45281071-e451e580-b500-11e8-8d54-de3ce9d96cd4.png)

I take the 'stop' method in below console.log('still load'). the loader won't stop/

im set for 10sec or 10000 , but it's not stopped.
