### ISSUE TITLE
Custom-custom loader config when custom loader in Project

### ISSUE THREAD

**Issue by arlekin183** [t-ho/ngx-ui-loader#50]
There is a custom loader in the project. It is implemented with NgxUiLoaderModule.forRoot().(paragraph 6 in the wiki). This loader works successfully in the whole project. 

Now I want to make a single loader for a separate situation. And I can not implement it. 
My single loader uses a common configuration and does not respond to properties in the markup ([fgsSize]= "50", for example).

I ask to implement the possibility of creating a loader with a separate configuration. For example, to create a separate configuration in an angular component and pass it as a parameter to the loader method.start().

Thanks.

**Comment by t-ho** [comment]
Hi,
You can implement your own service. Please see an example [here](https://stackblitz.com/edit/ngx-ui-loader-customized-service)
