### ISSUE TITLE
Angular 8 Support

### ISSUE THREAD

**Issue by pravinchandankhede** [t-ho/ngx-ui-loader#51]
Hi, we just migrated our app from Angular 7 to 8.1. However the loader is not working for Http request. It works during child route/module loading however doesn't work inside the child module components. It doesn't even throw any error.
Please confirm, if this library support Angular >8 or not and whats the issue if it does support.

**Comment by t-ho** [comment]
I confirm that the lib works as expected. There are some examples [here](https://github.com/t-ho/ngx-ui-loader/wiki/Demo).
Thanks.
