### ISSUE TITLE
Scrolling while loading screen is live

### ISSUE THREAD

**Issue by this-wastes-time** [t-ho/ngx-ui-loader#52]
Hi devs.
I am using ngx-ui-loader v7.2.2.
I have noticed that the loader does not prevent scrolling which in turn allows for the user to scroll down and show portions of the page that are then not covered by the loader.
I poked around and this occurs due to a css style for ".ngx-absolute-position" which sets "position: absolute!important"

Currently I believe in 2 solutions: 1. allowing scrolling but always behind the loader or 2. either scroll locking on load:
1. (preference) I think this line can simply be removed. There is already a "position: fixed" for the ".ngx-overlay" which will work. This allows for scrolling behind the loader and is none invasive to the user's project. 
2. Blocking the scrolling is just killing the overflow on the body and the showing the loader but it is a bit more invasive to the project.

Thanks
![loader scroll](https://user-images.githubusercontent.com/37585876/69033206-0ddb8c00-09a4-11ea-9fb1-5487e0f7f331.png)

**Comment by this-wastes-time** [comment]
![loader_scroll_gif](https://user-images.githubusercontent.com/37585876/69033505-be499000-09a4-11ea-8df5-0f44fc96247f.gif)

**Comment by this-wastes-time** [comment]
![loader_scroll](https://user-images.githubusercontent.com/37585876/69034151-26e53c80-09a6-11ea-97cb-f41ffd3887f7.gif)

**Comment by t-ho** [comment]
Hi,
You should place `<ngx-ui-loader></ngx-ui-loader>` in your root app template. [Here](https://github.com/t-ho/ngx-ui-loader/wiki/Demo) are some examples.
