### ISSUE TITLE
Calling loaderService .hide() sometimes fails to hide the loader

### ISSUE THREAD

**Issue by bot101** [t-ho/ngx-ui-loader#54]
Calling .hide on ngxService sometimes fails to hide the loader, even after calling within ngZone. Here
![ezgif com-crop (2)](https://user-images.githubusercontent.com/8009733/70724540-17ce8180-1cfb-11ea-8152-97d231e00cae.gif)

Even though I am calling hideAll() in 2 places, it still doesn't hide the loader. This happens frequently

**Comment by t-ho** [comment]
Please see demo and examples [here](https://tdev.app/ngx-ui-loader#demo)
