### ISSUE TITLE
Error: [ngx-ui-loader] - loaderId "x" does not exist. - browsing pages 

### ISSUE THREAD

**Issue by fdinardo** [t-ho/ngx-ui-loader#56]
Hi, 
I use a combination of "master" loader and "on page" loader.
When the content is still loading and a user browses another page, I get the error in the title.
All the loaders working as expected if the user waits for the content to finish loading and after that change the page.

Any idea on how to stop this error?

**Comment by JaydeepPatoliya** [comment]
Facing same issue.
<img width="1392" alt="Screenshot 2020-02-21 at 12 43 55 PM" src="https://user-images.githubusercontent.com/17637288/75012384-e23ad700-54a7-11ea-8220-9c1be8e129fb.png">

**Comment by t-ho** [comment]
Please see demo & examples [here](https://tdev.app/ngx-ui-loader#demo)

**Comment by fdinardo** [comment]
I am sorry, but I already looked at the documentation.
I have seen your demo and examples, and I am calling `API - NgxUiLoaderService` in the exact same way you do.

If I post something here, is because I am not able to figure out what is going on.
I mean, I think I get it, but I don't know how to stop it.

This error happen when a page is no fully load (http requests still going) and the user navigates to another route.

My master loader doesn't show this, neither the Router Loader (I called it `viewLoader`).
The problem is related to another loader that I defined on the page.
Let's say I have a page called `/app/posts` and another called `/app/posts/user`, when the user changes page from posts to posts/user the error is related to the previous page:
`Error: [ngx-ui-loader] - loaderId "postsLoader" does not exist`
Most of the time this loader is inside an ngOnInit function fetching data from API.

I can't use HttpLoader because I have multiple requests and multiple laoders in the same page.

I am sorry, maybe I am dumb, but I don't see how your comment is pointing me in the right direction to fix this

**Comment by t-ho** [comment]
Hi @fdinardo,
I am willing to help, but it is really hard for me to guess where the error came from. I would appreciate it if you could provide a basic setup/reproduction on [Stackblitz](https://stackblitz.com/).

Best regards,

**Comment by fdinardo** [comment]
Thanks for the answer, Yes It's hard to figure out an error without dealing with the code. You are right.

Here is a [Stackblitz](https://stackblitz.com/edit/angular-wtiqm2)

The way to reproduce the issue is to quickly click on "todos" and "users" without waiting them to finish loading.

Since I am using a test APIs the result it's very small and the payload is very light. So you have to be quick "switching" the pages.
In a real world application data returned from the API could be bigger than this one, so it's easier to make this error happen.

Let me know if you are able to reproduce!
Thanks

**Comment by t-ho** [comment]
Hi @fdinardo,

The lib will throw an error if you try to start or stop a non-existed loader. In your case, you have to **unsubscribe** (long) Http request properly. See an example [here](https://stackblitz.com/edit/ngx-ui-loader-http-unsubscribe). And see [this stackoverflow](https://stackoverflow.com/questions/46068908/how-to-cancel-unsubscribe-all-pending-http-requests-angular-4) to unsubscribe automatically when navigating away.

Anyway, I will update the lib so that it will print a `warning` instead of throwing an `error` when the loader does not exist.

I hope this will help.
Best regards,

**Comment by fdinardo** [comment]
Thanks, this is more than an "help"....
I appreciated!

IMHO, turning the error into a warning makes more sense.

Thanks again.
