### ISSUE TITLE
Controlling fade out duration

### ISSUE THREAD

**Issue by Roland55555** [t-ho/ngx-ui-loader#57]
Hello,

Where could I override the fade out duration of the loaders?

My site feels slower, because my http requests are pretty fast, but I show the loaders still and usually the fade out animation duration feels longer than the http request (I would like to use the NgxUiLoaderHttpModule).

Instead of this, I am forced not to use NgxUiLoaderHttpModule but to wrap the ngx-ui-loader component inside ngIf blocks to check if the http request is done or not, and instantly hide the loader, without that animation.

**Comment by ifynk** [comment]
Yes, it seems very lagy.

**Comment by ojathelonius** [comment]
Same issue here. The NgxUiLoaderHttpModule is quite convenient on paper, but makes it look like requests take forever. I'll take a look later to see if there is room for improvement on this

**Comment by cmwittrock** [comment]
You could try tweaking the threshold setting in the configuration for NgxUiLoaderModule. It may help make the page look a bit less sluggish. 
`NgxUiLoaderModule.forRoot({
      threshold: 0.1
    }),
`

**Comment by ojathelonius** [comment]
Thanks, I'll try it out !

Also correct me if I'm wrong, but currently in order to hide content while it's being loaded (and show the loader instead), one has to use `*ngIf="isLoading"` on this content.

Could it be possible instead to embed this content inside the loader as such :

```
<ngx-ui-loader>
<!-- This content will only be shown after done loading -->
</ngx-ui-loader>
```

I recall most React loaders worked this way

**Comment by cmwittrock** [comment]
I use the `*ngIf="isLoading"` method as well. You could play with the `overlayColor` setting and set the opacity to 1 so that you are unable to see your page content behind the spinner.

`overlayColor="rgba(40,40,40,1)"`

**Comment by t-ho** [comment]
Sorry for the late response.
FYI, in the version >= 9.0.0, you can set `fastFateOut` to `true` to reduce the fadeout duration.
