### ISSUE TITLE
Change Loader Text after some time...

### ISSUE THREAD

**Issue by sethigoldy** [t-ho/ngx-ui-loader#58]
I believe it will be a really nice addition if one can change the loading text after sometime lets say maybe 15 seconds or so depending on the use case. If in `NgxUiLoaderConfig` can accept two new parameter such as `waitingText` and `waitingTime` and then use them to change the text so that the user gets the idea that something is still going on. 
One particular case in which I need is when large data is being downloaded via api and the user just don't know whats happening.

Also, I can too help on code, just let me know.

**Comment by t-ho** [comment]
I don't support `waitingTime`, but you can create your own service and set timer to change the `text` property. [Here] is an example of a custom service.

**Comment by sethigoldy** [comment]
Please provide the link.
