### ISSUE TITLE
Update custom ngxUILoaderConfig

### ISSUE THREAD

**Issue by dhavalsolankislk** [t-ho/ngx-ui-loader#59]
Hello,
I am using ngxUILoader with custom configuration defined in app.module.ts. I want to change fgsColor property runtime as defined in my theme in whole application where loader is used. How can I achieve this.

**Comment by t-ho** [comment]
You can create your own service. See a similar example [here](https://stackblitz.com/edit/ngx-ui-loader-customized-service)

**Comment by dhavalsolankislk** [comment]
Hello,

Can you provide code in which we can call method through provider to update configuration runtime

**Comment by t-ho** [comment]
Hi @dhavalsolankislk ,

Here is an [example](https://stackblitz.com/edit/ngx-ui-loader-customized-service) that shows you a basic idea on how to create your own service wrapping `NgxUiLoaderService`.
