### ISSUE TITLE
getting error when build using visual studio

### ISSUE THREAD

**Issue by BhushanChandak** [t-ho/ngx-ui-loader#6]
I integrate ngx-ui-loader with my project Angular 5.2, It is working fine.
But when I build with visual studio it is showing error like

`Error:	TS1066	(TS) In ambient enum declarations member initializer must be constant expression.	Portal (tsconfig project)	C:\MCS_Project\MMCS\Products-TS\Repository\DEV\CTS-V1.0.0.1\CTS\Web\Portal\node_modules\ngx-ui-loader\lib\core\ngx-ui-loader.enums.d.ts
`
![error](https://user-images.githubusercontent.com/21455547/49223698-76350480-f405-11e8-869c-efb4f1abd130.PNG)
 please find screenshot.

Did all trial and error of updating typescript and etc although same error coming.

Thank you in advance.

**Comment by BhushanChandak** [comment]
@t-ho Could you please help me on this?

**Comment by t-ho** [comment]
Hi @BhushanChandak, 

I have tried to build in production mode with angular 5, it worked properly. I have put the test example [here](https://github.com/t-ho/angular-v5-test/tree/ngx-ui-loader), you can check it yourself.
```shell
git clone -b ngx-ui-loader https://github.com/t-ho/angular-v5-test.git
cd angular-v5-test
npm install
./node_modules/@angular/cli/bin/ng build --prod
# OR
ng build --prod
``` 

I don't use MS Visual Studio (windows), so can't help you. But you should try:
1. For your app (angular 5.2), you should install ngx-ui-loader@1.2.5
```shell
npm install --save ngx-ui-loader@1.2.5
```
2. Remove `node_modules` in your app, then reinstall packages:
```shell
rm -Rf node_modules && npm install
```
3. Should try to build your app with local `ng`
```shell
./node_modules/@angular/cli/bin/ng build --prod
```
I hope this will help.
Thanks.
