### ISSUE TITLE
Reducing minTime for a loader below the global constant

### ISSUE THREAD

**Issue by Zakkski** [t-ho/ngx-ui-loader#64]
I am trying to use the basic loader on an app I'm developing and I am noticing that the minimum time for the loader to be active is too long for the app. Most of the resources load pretty quick so 300ms is still too long to have the loader. I tried looking at the source code to figure out how to configure it shorter but it looks like it can't be configured any lower than 300ms. Is there a reason for this and are there other ways that I could reduce that time?

**Comment by t-ho** [comment]
Hello @Zakkski 

Thank you for using `ngx-ui-loader`.

I just want to make sure the spinner is shown in really fast tasks. But now I will update the lib so that you can set `minTime` to your desired value.

**Comment by t-ho** [comment]
Updated!

**Comment by Zakkski** [comment]
Thank you! I appreciate it!
