### ISSUE TITLE
"exclude" does not work unless protocol and domain are specified

### ISSUE THREAD

**Issue by engemasa** [t-ho/ngx-ui-loader#7]
When using the `NgxUiLoaderHttpModule` and setting an API call for exclusion, the logic within [ngx-ui-loader-http.interceptor.ts](https://github.com/t-ho/ngx-ui-loader/blob/master/projects/ngx-ui-loader/src/lib/http/ngx-ui-loader-http.interceptor.ts): line 40 compares the entire request URL (`req.url`) which includes the protocal and domain but the exclusion (as per the [documentation](https://github.com/t-ho/ngx-ui-loader#82-parameters-of-forroot-method)) only is the `pathname` and beyond. Becasue of this, the exclusion will never work and the loader will always be shown even when it's not desired.

My solution for this (for now) was to include my environment for the api in each exclusion:

```
imports: [
  ...
  NgxUiLoaderHttpModule.forRoot({ exclude: [environment.baseAPIUrl + '/my/endpoint?param1=1&param2=0'] }),
  ...
]
```

**Comment by t-ho** [comment]
Sorry for ambiguous documentation. When I wrote the documentation, I assumed that the url is within the app such as `this.http.get('/api/logout').subscribe(res => {...});`

Anyway, I have updated README. ([311bc01](https://github.com/t-ho/ngx-ui-loader/commit/311bc01))

Thank you very much for your feedback.

**Comment by engemasa** [comment]
Excellent! Thank you!
