### ISSUE TITLE
I don't get how I use this as a file upload progress bar?

### ISSUE THREAD

**Issue by grimace** [t-ho/ngx-ui-loader#70]
**Describe the bug**
I'd like to pass the percentage or progress value in to the control to get the progress bar to move during a file upload, but it's unclear how to do that in the docs.

**Comment by t-ho** [comment]
Hi @grimace,

This lib does not support that. I think you should give [ngx-progressbar](https://github.com/MurhafSousli/ngx-progressbar) a try.
