### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by shawsank** [t-ho/ngx-ui-loader#79]
ERROR in node_modules/ngx-ui-loader/lib/core/ngx-ui-loader.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved 
to an NgModule class.
    
    This likely means that the library (ngx-ui-loader) which declares NgxUiLoaderModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    3 export declare class NgxUiLoaderModule {
                           ~~~~~~~~~~~~~~~~~
    src/app/app.module.ts:36:14 - error NG6002: Appears in the NgModule.imports of AppBrowserModule, but itself has errors
    
    36 export class AppModule { }
                    ~~~~~~~~~
    

Date: 2020-08-09T06:04:58.004Z - Hash: 08511d948745f3341165
25 unchanged chunks
chunk {main} main.js, main.js.map (main) 40.3 kB [initial] [rendered]
Time: 787ms
: Compiled successfully.
    
    ERROR in node_modules/ngx-ui-loader/lib/core/ngx-ui-loader.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved 
to an NgModule class.
    
    This likely means that the library (ngx-ui-loader) which declares NgxUiLoaderModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    3 export declare class NgxUiLoaderModule {
                           ~~~~~~~~~~~~~~~~~
    src/app/app.module.ts:36:14 - error NG6002: Appears in the NgModule.imports of AppBrowserModule, but itself has errors
    
    36 export class AppModule { }
                    ~~~~~~~~~
    src/app/app.component.html:14:3 - error NG8001: 'ngx-ui-loader' is not a known element:
    1. If 'ngx-ui-loader' is an Angular component, then verify that it is part of this module.
    2. If 'ngx-ui-loader' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
    14   <ngx-ui-loader></ngx-ui-loader>
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/app.component.ts:5:16
        5   templateUrl: './app.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component AppComponent.
    src/app/app.component.html:15:3 - error NG8001: 'router-outlet' is not a known element:
    1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
    2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by zohar1000** [comment]
Hi @shawsank, I currently use ngx-ui-loader in 2 projects, one is angular 9 and the other is angular 10, and they both works fine.
check out [this link](https://github.com/angular/angular/issues/36060), they talk about the same problem.

**Comment by asithade** [comment]
So I was just having a similar issue, and I was able to fix it by rearranging my import modules. 

In my case, I was calling `LoadingBarRouterModule` before the main module `LoadingBarModule`. Check to see if you are loading the NgxUiLoader module before another required module and move it below that.
