### ISSUE TITLE
Can not apply Blur and I only run config on HTML/pub in Angular 10

### ISSUE THREAD

**Issue by TuanViet2141** [t-ho/ngx-ui-loader#82]
**Describe the bug**
Can not apply Blur and I only run config on HTML/pub file in Angular 10 can not run in app.module.ts file 

 const ngxUiLoaderConfig: NgxUiLoaderConfig = {
   blur: 7,
   fgsColor: 'red',
   fgsPosition: POSITION.centerCenter,
   fgsSize: 40,
   fgsType: SPINNER.squareJellyBox,
   pbDirection: PB_DIRECTION.leftToRight, 
   pbThickness: 5, 
   masterLoaderId: "master",
   text: "LOADING..." 
 }

After I put it in my App.Module.ts file it is not run but in Html file it run well.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.16.76

**Comment by t-ho** [comment]
Hi @TuanViet2141,

I guess you might forget to import the module with the custom configuration.

```javascript
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    // Import NgxUiLoaderModule with custom configuration globally
    NgxUiLoaderModule.forRoot(ngxUiLoaderConfig)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
```

Please see [here](https://tdev.app/ngx-ui-loader#custom-configuration-for-ngxuiloadermodule)
