### ISSUE TITLE
Change text value dependent on component that is executing start()

### ISSUE THREAD

**Issue by fromage9747** [t-ho/ngx-ui-loader#9]
Is there any way to pass custom configurations when executing start()?

For example, the default "text" I have included in the for root config is "loading...".  I would like to change that text when executing start() in another component. 
For example this.ngxservice.start({ text: 'validating...' });

Could this be configured for all the configurations that are available?

**Comment by t-ho** [comment]
Hi @fromage9747,

You can write your own service wrapping ngxUiLoaderService. See example [here](https://stackblitz.com/edit/ngx-ui-loader-customized-service?file=src%2Fapp%2Floader.service.ts).

Thank you.

**Comment by fromage9747** [comment]
@t-ho Excellent, thank you.  Tried and tested.  Confirmed working in my own complex app.
