### ISSUE TITLE
blur not working for square-jelly-box

### ISSUE THREAD

**Issue by aysha-statvalu** [t-ho/ngx-ui-loader#99]
i tried this below:
<ngx-ui-loader [fgsColor]="'#cad3c1'" [fgsType]="'square-jelly-box'" [hasProgressBar]="false" [loaderId]="'square'"></ngx-ui-loader>
NgxUiLoaderModule.forRoot({blur: 20}),
<div ngxUiLoaderBlurred [blur]="10">
    <router-outlet></router-outlet>
</div>
![Screenshot (81)](https://user-images.githubusercontent.com/82865585/139191004-70db4091-9911-43ae-b048-b9813667bb2a.png)

**Comment by t-ho** [comment]
Hi @aysha-statvalu,
Make sure you are using the `ngxUiLoaderBlurred` directive on the parent container. Please see [here](https://tdev.app/ngx-ui-loader#ngxuiloaderblurred-directive).

**Comment by aysha-statvalu** [comment]
only working for single <ngx-ui-loader></ngx-ui-loader> not for both like this

<ngx-ui-loader></ngx-ui-loader>
<ngx-ui-loader [fgsColor]="'#cad3c1'" [fgsType]="'square-jelly-box'" [hasProgressBar]="false" [loaderId]="'square'">
